---
Name: sitemap3
After: 'framework/*', 'cms/*'
---
SiteMapPage:
  hidefrommap:
    ClassName:
      - ErrorPage
      - SiteMapPage
  theme: default
  autobuildpage: true
SiteTree:
  extensions:
    - SiteMapSiteTreeExtension
